// Code generated by "core generate"; DO NOT EDIT.

package deep

import (
	"log"

	"cogentcore.org/core/enums"
	"github.com/emer/emergent/v2/emer"
)

var _PrjnTypeValues = []PrjnType{4}

// PrjnTypeN is the highest valid value for type PrjnType, plus one.
const PrjnTypeN PrjnType = 5

var _PrjnTypeValueMap = map[string]PrjnType{`CTCtxt_`: 4}

var _PrjnTypeDescMap = map[PrjnType]string{4: ``}

var _PrjnTypeMap = map[PrjnType]string{4: `CTCtxt_`}

// String returns the string representation of this PrjnType value.
func (i PrjnType) String() string {
	return enums.StringExtended[PrjnType, emer.PrjnType](i, _PrjnTypeMap)
}

// SetString sets the PrjnType value from its string representation,
// and returns an error if the string is invalid.
func (i *PrjnType) SetString(s string) error {
	return enums.SetStringExtended(i, (*emer.PrjnType)(i), s, _PrjnTypeValueMap)
}

// Int64 returns the PrjnType value as an int64.
func (i PrjnType) Int64() int64 { return int64(i) }

// SetInt64 sets the PrjnType value from an int64.
func (i *PrjnType) SetInt64(in int64) { *i = PrjnType(in) }

// Desc returns the description of the PrjnType value.
func (i PrjnType) Desc() string {
	if str, ok := _PrjnTypeDescMap[i]; ok {
		return str
	}
	return emer.PrjnType(i).Desc()
}

// PrjnTypeValues returns all possible values for the type PrjnType.
func PrjnTypeValues() []PrjnType {
	es := emer.PrjnTypeValues()
	res := make([]PrjnType, len(es))
	for i, e := range es {
		res[i] = PrjnType(e)
	}
	res = append(res, _PrjnTypeValues...)
	return res
}

// Values returns all possible values for the type PrjnType.
func (i PrjnType) Values() []enums.Enum {
	es := emer.PrjnTypeValues()
	les := len(es)
	res := make([]enums.Enum, les+len(_PrjnTypeValues))
	for i, d := range es {
		res[i] = d
	}
	for i, d := range _PrjnTypeValues {
		res[i+les] = d
	}
	return res
}

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i PrjnType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *PrjnType) UnmarshalText(text []byte) error {
	if err := i.SetString(string(text)); err != nil {
		log.Println("PrjnType.UnmarshalText:", err)
	}
	return nil
}

var _LayerTypeValues = []LayerType{4, 5}

// LayerTypeN is the highest valid value for type LayerType, plus one.
const LayerTypeN LayerType = 6

var _LayerTypeValueMap = map[string]LayerType{`CT_`: 4, `TRC_`: 5}

var _LayerTypeDescMap = map[LayerType]string{4: ``, 5: ``}

var _LayerTypeMap = map[LayerType]string{4: `CT_`, 5: `TRC_`}

// String returns the string representation of this LayerType value.
func (i LayerType) String() string {
	return enums.StringExtended[LayerType, emer.LayerType](i, _LayerTypeMap)
}

// SetString sets the LayerType value from its string representation,
// and returns an error if the string is invalid.
func (i *LayerType) SetString(s string) error {
	return enums.SetStringExtended(i, (*emer.LayerType)(i), s, _LayerTypeValueMap)
}

// Int64 returns the LayerType value as an int64.
func (i LayerType) Int64() int64 { return int64(i) }

// SetInt64 sets the LayerType value from an int64.
func (i *LayerType) SetInt64(in int64) { *i = LayerType(in) }

// Desc returns the description of the LayerType value.
func (i LayerType) Desc() string {
	if str, ok := _LayerTypeDescMap[i]; ok {
		return str
	}
	return emer.LayerType(i).Desc()
}

// LayerTypeValues returns all possible values for the type LayerType.
func LayerTypeValues() []LayerType {
	es := emer.LayerTypeValues()
	res := make([]LayerType, len(es))
	for i, e := range es {
		res[i] = LayerType(e)
	}
	res = append(res, _LayerTypeValues...)
	return res
}

// Values returns all possible values for the type LayerType.
func (i LayerType) Values() []enums.Enum {
	es := emer.LayerTypeValues()
	les := len(es)
	res := make([]enums.Enum, les+len(_LayerTypeValues))
	for i, d := range es {
		res[i] = d
	}
	for i, d := range _LayerTypeValues {
		res[i+les] = d
	}
	return res
}

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i LayerType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *LayerType) UnmarshalText(text []byte) error {
	if err := i.SetString(string(text)); err != nil {
		log.Println("LayerType.UnmarshalText:", err)
	}
	return nil
}
