// Code generated by "stringer -type=NeurFlags"; DO NOT EDIT.

package leabra

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NeurOff-0]
	_ = x[NeurHasExt-1]
	_ = x[NeurHasTarg-2]
	_ = x[NeurHasCmpr-3]
	_ = x[NeurFlagsN-4]
}

const _NeurFlags_name = "NeurOffNeurHasExtNeurHasTargNeurHasCmprNeurFlagsN"

var _NeurFlags_index = [...]uint8{0, 7, 17, 28, 39, 49}

func (i NeurFlags) String() string {
	if i < 0 || i >= NeurFlags(len(_NeurFlags_index)-1) {
		return "NeurFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NeurFlags_name[_NeurFlags_index[i]:_NeurFlags_index[i+1]]
}

func (i *NeurFlags) FromString(s string) error {
	for j := 0; j < len(_NeurFlags_index)-1; j++ {
		if s == _NeurFlags_name[_NeurFlags_index[j]:_NeurFlags_index[j+1]] {
			*i = NeurFlags(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: NeurFlags")
}
