// Code generated by "stringer -type=TimeScales"; DO NOT EDIT.

package leabra

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

const _TimeScales_name = "CycleFastSpikeQuarterPhaseBetaCycleAlphaCycleThetaCycleEventTrialSequenceBlockEpochRunExptSceneEpisodeTimeScalesN"

var _TimeScales_index = [...]uint8{0, 5, 14, 21, 26, 35, 45, 55, 60, 65, 73, 78, 83, 86, 90, 95, 102, 113}

func (i TimeScales) String() string {
	if i < 0 || i >= TimeScales(len(_TimeScales_index)-1) {
		return "TimeScales(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimeScales_name[_TimeScales_index[i]:_TimeScales_index[i+1]]
}

func (i *TimeScales) FromString(s string) error {
	for j := 0; j < len(_TimeScales_index)-1; j++ {
		if s == _TimeScales_name[_TimeScales_index[j]:_TimeScales_index[j+1]] {
			*i = TimeScales(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: TimeScales")
}
