// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package leabra

const (
	Version     = "v1.1.45"
	GitCommit   = "09456d2"          // the commit JUST BEFORE the release
	VersionDate = "2022-02-02 12:24" // UTC
)
