// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package leabra

const (
	Version     = "v1.1.35"
	GitCommit   = "53660ac" // the commit JUST BEFORE the release
	VersionDate = "2021-08-11 06:43" // UTC
)

