// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package leabra

const (
	Version     = "v1.1.33"
	GitCommit   = "329158f" // the commit JUST BEFORE the release
	VersionDate = "2021-04-29 11:00" // UTC
)

