// Code generated by "go run gen/reclistgen.go -type TrialInstance -output data/trial_instance_recs.go". DO NOT EDIT

package data

import (
	"errors"
	"math/rand"
)

type TrialInstanceList []*TrialInstance

type TrialInstanceRecs struct {
	Records TrialInstanceList
	Index   []int
	INext   int
	NRead   int
	Order   DataLoopOrder
}

func NewTrialInstanceRecs(data TrialInstanceList) *TrialInstanceRecs {
	recs := new(TrialInstanceRecs)
	if data == nil {
		recs.Records = TrialInstanceList{}
		recs.Index = []int{}
	} else {
		recs.Records = data
		recs.Index = IntSequence(0, len(data), 1)
	}
	recs.INext = -1
	recs.NRead = 0
	return recs
}

// Set to initial state just before reading
func (recs *TrialInstanceRecs) Reset() {
	recs.NRead = 0
	recs.INext = -1
}

// Set the entire index array for the TrialInstanceRecs
func (recs *TrialInstanceRecs) SetIndex(ix []int) error {
	if len(ix) > len(recs.Records) {
		return errors.New("supplied index is longer than data")
	}
	recs.Index = ix
	recs.Reset()
	return nil
}

func (recs *TrialInstanceRecs) SetPos(i int) {
	recs.INext = i - 1
}
func (recs *TrialInstanceRecs) Length() int {
	return len(recs.Records)
}
func (recs *TrialInstanceRecs) Cur() int {
	return recs.INext + 1
}

func (recs *TrialInstanceRecs) SetOrder(order DataLoopOrder) {
	recs.Order = order
	if order == SEQUENTIAL {
		recs.Sequential()
	} else if order == PERMUTED {
		recs.Permute()
	}
	recs.Reset()
}

func (recs *TrialInstanceRecs) Permute() {
	recs.Index = rand.Perm(len(recs.Records))
}
func (recs *TrialInstanceRecs) Sequential() {
	recs.Index = IntSequence(0, len(recs.Records), 1)
}
func (recs *TrialInstanceRecs) GetIndex() []int {
	return recs.Index
}
func (recs *TrialInstanceRecs) WriteNext(rec *TrialInstance) {
	recs.Records = append(recs.Records, rec)
	recs.Index = append(recs.Index, len(recs.Records)-1)
}
func (recs *TrialInstanceRecs) ReadNext() *TrialInstance {
	recs.NRead++
	if recs.Order == RANDOM {
		return recs.Records[rand.Intn(len(recs.Records))]
	} else {
		recs.INext++
		return recs.Records[recs.Index[recs.INext]]
	}
}

func (recs *TrialInstanceRecs) Peek() *TrialInstance {
	if recs.AtEnd() {
		return nil
	}
	return recs.Records[recs.Index[recs.INext+1]]
}
func (recs *TrialInstanceRecs) AtEnd() bool {
	return recs.NRead >= len(recs.Records)
}
