// Code generated by "stringer -type=PathType"; DO NOT EDIT.

package glong

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NMDA_-4]
	_ = x[PathTypeN-5]
}

const _PathType_name = "NMDA_PathTypeN"

var _PathType_index = [...]uint8{0, 5, 14}

func (i PathType) String() string {
	i -= 4
	if i < 0 || i >= PathType(len(_PathType_index)-1) {
		return "PathType(" + strconv.FormatInt(int64(i+4), 10) + ")"
	}
	return _PathType_name[_PathType_index[i]:_PathType_index[i+1]]
}

func StringToPathType(s string) (PathType, error) {
	for i := 0; i < len(_PathType_index)-1; i++ {
		if s == _PathType_name[_PathType_index[i]:_PathType_index[i+1]] {
			return PathType(i + 4), nil
		}
	}
	return 0, errors.New("String: " + s + " is not a valid option for type: PathType")
}
