// Code generated by "stringer -type=RunState"; DO NOT EDIT.

package stepper

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Created-0]
	_ = x[Stopped-1]
	_ = x[Paused-2]
	_ = x[Stepping-3]
	_ = x[Running-4]
	_ = x[RunStateN-5]
}

const _RunState_name = "CreatedStoppedPausedSteppingRunningRunStateN"

var _RunState_index = [...]uint8{0, 7, 14, 20, 28, 35, 44}

func (i RunState) String() string {
	if i < 0 || i >= RunState(len(_RunState_index)-1) {
		return "RunState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunState_name[_RunState_index[i]:_RunState_index[i+1]]
}
