// Code generated by "stringer -type=DorsalVentral"; DO NOT EDIT.

package pbwm

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Dorsal-0]
	_ = x[Ventral-1]
	_ = x[DorsalVentralN-2]
}

const _DorsalVentral_name = "DorsalVentralDorsalVentralN"

var _DorsalVentral_index = [...]uint8{0, 6, 13, 27}

func (i DorsalVentral) String() string {
	if i < 0 || i >= DorsalVentral(len(_DorsalVentral_index)-1) {
		return "DorsalVentral(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DorsalVentral_name[_DorsalVentral_index[i]:_DorsalVentral_index[i+1]]
}

func (i *DorsalVentral) FromString(s string) error {
	for j := 0; j < len(_DorsalVentral_index)-1; j++ {
		if s == _DorsalVentral_name[_DorsalVentral_index[j]:_DorsalVentral_index[j+1]] {
			*i = DorsalVentral(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: DorsalVentral")
}
